/*
====================
GOAL: IMPROVE BOTTOM LINE (PROFIT?) THROUGH MIX OF OPERATIONS/CULINARY/PRICING CHANGES

DATA:
    - 2 HOSPITALS (A/B)
    - LOCATED IN SAME GEOGRAPHIC AREA (5 MI APART)
    - DATA IS POS TRANSACTION DATA
    - BEVERAGES HAVE HIGHEST MARGIN (70%) VS FOOD (35%)
    
    
DATA COLUMNS
    - PAYMENT GROUP (CASH/CREDIT/DEPARTMENT CHARGE/FREE MEALS/PAYROLL DEDUCT/UNCATEGORIZED)
    - CHECK ID > INDIVIDUAL TICKET
        - CHECK ID IS INDIVIDUAL TICKET, TRANSACTION ID IS EACH ITEM ON TICKET
    - SALE DATE (1/1/24 - 6/30/24)
    - CATEGORY 35 GROUPS, LONG LEFT TAIL
        - ARE PRODUCTS IN TAIL ALWAYS PURCHASED TOGETHER? COULD JUSTIFY KEEPING
        - FEW PRODUCTS ARE IN 2 CATEGORIES I.E. ALMONDS (ALSO HIDDEN SPACES)
OUTPUT
    - PURCHASING HABITS (TIME OF DAY, PRODUCT MIX, SEASONAILITY)
        - REVIEW FOR HOLIDAYS/HIGHEST HOSPITALIZATION TIMES
        - DAY SEASONALITY/MONTH SEASONALITY
        - COMPLIMENTARY GOODS/SUBSTITUTE
    - SITE COMPARISION (REVENUE, CHECK AVG, ITEM/TRANSACTIONS, MoM GROWTH)
    - ITEM ANALYSIS TO CONDENSE/STREAMLINE MENU OFFERINGS
        - PERCENTILES TO REVIEW SPREAD OF DATA, CUT OFF LONG TAILS?
    - OPERATION RECOMMENDATIONS
    - PRICE OPTIMIZATION TO MAKE HEALTHY FOODS LOWER COST
        -NLP TO FLAG HEALTHY ITEMS?
*/

SELECT TRIM(UPPER(HOSPITAL)) AS HOSPITAL
    ,TRIM(UPPER(`PAYMENT GROUP`)) AS PMT_GRP
    ,`SALE DATE` AS SALES_DT
    ,`SALE TIME` AS SALES_TM
    ,`CHECK ID` AS CHECK_ID
    ,`TRANSACTION ID` AS TRANS_ID
    ,TRIM(UPPER(`CATEGORY`)) AS CATEGORY
    ,TRIM(UPPER(`ITEM NAME`)) AS ITEM_NM
    ,`GROSS REVENUE` AS GROSS_REV
FROM couch2coding.HealthRetail.HEALTH_RETAIL







