/*
====================
GOAL: IMPROVE BOTTOM LINE (PROFIT?) THROUGH MIX OF OPERATIONS/CULINARY/PRICING CHANGES

DATA:
    - 2 HOSPITALS (A/B)
    - LOCATED IN SAME GEOGRAPHIC AREA (5 MI APART)
    - DATA IS POS TRANSACTION DATA
    - BEVERAGES HAVE HIGHEST MARGIN (70%) VS FOOD (35%)
    
    
DATA COLUMNS
    - PAYMENT GROUP (CASH/CREDIT/DEPARTMENT CHARGE/FREE MEALS/PAYROLL DEDUCT/UNCATEGORIZED)
    - CHECK ID > INDIVIDUAL TICKET
        - CHECK ID IS INDIVIDUAL TICKET, TRANSACTION ID IS EACH ITEM ON TICKET
    - SALE DATE (1/1/24 - 6/30/24)
    - CATEGORY 35 GROUPS, LONG LEFT TAIL
        - ARE PRODUCTS IN TAIL ALWAYS PURCHASED TOGETHER? COULD JUSTIFY KEEPING
        - FEW PRODUCTS ARE IN 2 CATEGORIES I.E. ALMONDS (ALSO HIDDEN SPACES)
OUTPUT
    - PURCHASING HABITS (TIME OF DAY, PRODUCT MIX, SEASONAILITY)
        - REVIEW FOR HOLIDAYS/HIGHEST HOSPITALIZATION TIMES
        - DAY SEASONALITY/MONTH SEASONALITY
        - COMPLIMENTARY GOODS/SUBSTITUTE
    - SITE COMPARISION (REVENUE, CHECK AVG, ITEM/TRANSACTIONS, MoM GROWTH)
    - ITEM ANALYSIS TO CONDENSE/STREAMLINE MENU OFFERINGS
        - PERCENTILES TO REVIEW SPREAD OF DATA, CUT OFF LONG TAILS?
    - OPERATION RECOMMENDATIONS
    - PRICE OPTIMIZATION TO MAKE HEALTHY FOODS LOWER COST
        -NLP TO FLAG HEALTHY ITEMS?
*/
-- CREATE OR REPLACE TABLE `couch2coding.HealthRetail.HEALTH_RETAIL` AS 
-- CREATE OR REPLACE TABLE `couch2coding.HealthRetail.HEALTH_RETAIL` AS 
WITH BASE AS
(
  SELECT *
    ,DENSE_RANK() OVER(ORDER BY RUNNING_CAT_REV DESC) AS CAT_REV_RANK
    ,DENSE_RANK() OVER(ORDER BY RUNNING_ITM_REV DESC) AS ITM_REV_RANK
    ,DENSE_RANK() OVER(ORDER BY RUNNING_HOSP_CAT_REV DESC) AS HOSP_CAT_RANK
    ,DENSE_RANK() OVER(ORDER BY RUNNING_HOSP_ITM_REV DESC) AS HOSP_ITM_RANK
  FROM
    (
      SELECT TRIM(UPPER(HOSPITAL)) AS HOSPITAL
          ,TRIM(UPPER(`PAYMENT GROUP`)) AS PMT_GRP
          ,`SALE DATE` AS SALES_DT
          ,`SALE TIME` AS SALES_TM
          ,`CHECK ID` AS CHECK_ID
          ,`TRANSACTION ID` AS TRANS_ID
          ,TRIM(UPPER(`CATEGORY`)) AS CATEGORY
          ,TRIM(UPPER(`ITEM NAME`)) AS ITEM_NM
          ,`GROSS REVENUE` AS GROSS_REV
          ,SUM(`GROSS REVENUE`) OVER(PARTITION BY CATEGORY) AS RUNNING_CAT_REV
          ,SUM(`GROSS REVENUE`) OVER(PARTITION BY `ITEM NAME`) AS RUNNING_ITM_REV
          ,SUM(`GROSS REVENUE`) OVER(PARTITION BY CATEGORY, HOSPITAL) AS RUNNING_HOSP_CAT_REV
          ,SUM(`GROSS REVENUE`) OVER(PARTITION BY `ITEM NAME`,HOSPITAL) AS RUNNING_HOSP_ITM_REV
      FROM couch2coding.HealthRetail.RAW_HOSP_DATA
    )
)

,LOW_SELLERS AS
(
  SELECT ITEM_NM
    ,SUM(GROSS_REV) AS N_SALES
    ,COUNT(CHECK_ID) AS N_CHECKS
    ,COUNT(DISTINCT SALES_DT) AS N_DAYS
    ,COUNT(DISTINCT EXTRACT(MONTH FROM SALES_DT)) AS N_MONTH
  FROM BASE
  WHERE SALES_DT <= '2024-04-01'
  GROUP BY ALL
  HAVING N_DAYS <= 10
    AND N_MONTH > 1
)

SELECT BASE.*
  --IF AN ITEM IS IN OUR LOW SELLERS 0 OTHERWISE 1
  ,IF(LOW_SELLERS.ITEM_NM IS NULL,1,0) AS FREQ_SELLER
FROM BASE
LEFT JOIN LOW_SELLERS
  USING(ITEM_NM)
where gross_rev < 0
and check_id = 26374318
ORDER BY 2 DESC


